name: ESLint check
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
    
      - name: Install NPM dependencies
        run: npm install

      - name: Test ESLint 🛂
        run: npm run checkWithLint



